/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as SignUpImport } from './routes/SignUp'
import { Route as IndexImport } from './routes/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AuthenticatedDashboardIndexImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAboutIndexImport } from './routes/_authenticated/about/index'

// Create/Update Routes

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const SignUpRoute = SignUpImport.update({
  id: '/SignUp',
  path: '/SignUp',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAboutIndexRoute = AuthenticatedAboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/SignUp': {
      id: '/SignUp'
      path: '/SignUp'
      fullPath: '/SignUp'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/about/': {
      id: '/_authenticated/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardIndexImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedAboutIndexRoute: typeof AuthenticatedAboutIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutIndexRoute: AuthenticatedAboutIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/SignUp': typeof SignUpRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/about': typeof AuthenticatedAboutIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/SignUp': typeof SignUpRoute
  '': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/about': typeof AuthenticatedAboutIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/SignUp': typeof SignUpRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/_authenticated/about/': typeof AuthenticatedAboutIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/SignUp' | '' | '/login' | '/about' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/SignUp' | '' | '/login' | '/about' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/SignUp'
    | '/_authenticated'
    | '/login/'
    | '/_authenticated/about/'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignUpRoute: typeof SignUpRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignUpRoute: SignUpRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/SignUp",
        "/_authenticated",
        "/login/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/SignUp": {
      "filePath": "SignUp.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/about/",
        "/_authenticated/dashboard/"
      ]
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/_authenticated/about/": {
      "filePath": "_authenticated/about/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard/": {
      "filePath": "_authenticated/dashboard/index.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
